<a href="https://colab.research.google.com/github/Vijaychethan/AIML-Project1/blob/main/heart_disease.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
df = pd.read_csv('https://talentcocomedia.s3.amazonaws.com/ml-assets/heart-disease.csv')

In [3]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

Parameters used in heart diagnosis :

*  **Age** : 
    With age, the disease burden increases. Interestingly, the same pathways that modulate longevity affect the development of multiple, age-related pathologies. Ageing as a disease risk factor can be thought of as the accrued effect of a finite number of evolutionarily conserved pathways.
*   **sex** : 
 while the frequency of CVD tends to be lower in women before menopause than in men, the frequency dramatically increases after menopause, when it accounts for approximately one out of every three deaths in women.
In addition, many of the "classic" signs and symptoms of CVD are based on medical research largely performed in men. For example, many think of chest pain as a typical symptom of a heart attack. But while both men and women can experience chest pain, women are more likely to experience atypical symptoms such as nausea or vomiting, shortness of breath, dizziness, or no symptoms at all. What’s more, 64% of women who die suddenly of coronary heart disease had no previous symptoms.
*   **cp**(Chest pain type) :
*   Typical angina (TA) is defined as substernal chest pain precipitated by 
physical exertion or emotional stress and relieved with rest or nitroglycerin. Women and elderly patients are usually have atypical symptoms both at rest and during stress, often in the setting of nonobstructive coronary artery disease (CAD).
*   Atypical angina:  person is said to suffer from atypical chest pain, which unlike typical chest pain, doesn’t occur in the sternum and may radiate to other parts of the body.
*   non-anginal pain:A chest pain is very likely nonanginal if its duration is over 30 minutes or less than 5 seconds, it increases with inspiration, can be brought on with one movement of the trunk or arm, can be brought on by local fingers pressure, or bending forward, or it can be relieved immediately on lying down. 
*   asymptomatic : Asymptomatic heart attacks medically known as silent myocardial infarction (SMI) annually accounts for around 45-50% of morbidities due to cardiac ailments and even premature deaths in India. The incidences among middle aged people experiencing SMI is twice likely to develop in males than females. The symptoms of SMI being very mild in comparison to an actual heart attack; it is described as a silent killer. Because sometimes there is no cardiac arrest symptoms. 



*   **trestbps** : Blood pressure
*   **chol** : represents the amount of total cholesterol in their blood.
*   **fbs** : This measures your blood sugar after an overnight fast (not eating) ,to diagnose prediabetes, diabetes or gestational diabetes.
*   **restecg** : records the electrical activity of your heart while you are at rest. It provides information about your heart rate and rhythm, and can also show if there is enlargement of the heart, or evidence of a previous heart attack.
*   **thalach** : maximum heart rate achieved,Maximum heart rates can vary from person to person and they are not an indicator of physical fitness. In other words, it doesn't rise as you get stronger or faster, and it doesn't mean that someone with a higher MHR is in better shape than you.However, knowing your max HR can help you track your fitness progress and determine your target heart rate. That can give you a more exact method of determining your exercise intensity 
*   **exang** : exercise induced angina=> It usually happens during activity (exertion) and goes away with rest or angina medication. For example, pain that comes on when you're walking uphill or in the cold weather may be angina
*   **oldpeak** : ST depression induced by exercise relative to rest
*   **slope** : the slope of the peak exercise ST segment
-- Value 1: upsloping
-- Value 2: flat
-- Value 3: downsloping
*   **ca** : number of major vessels (0-3) colored by flourosopy
*   **thal** : Thal : displays the thalassemia :
3 = normal
6 = fixed defect
7 = reversible defect
*   **num(Predicted value)**:
 diagnosis of heart disease (angiographic disease status)
-- Value 0: < 50% diameter narrowing
-- Value 1: > 50% diameter narrowing


here all the parameters are used to predict the num parameter that defines the diagnosis of heart disease


in the above table we observe that all the target values are 1 i.e all the patients are diagnosed with heart disease